### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by daragao** [clearmatics/ion#14]
* Add docker files
* Setup Continuous Integration

**Comment by HarryR** [comment]
See: https://github.com/clearmatics/ion/issues/51 and https://github.com/clearmatics/ion/pull/74

I have re-added the Dockerfiles you removed..........

I also added back in the PyInstaller build stuff, and Python wheel/egg builds (should you want to publish this to PyPi)

**Comment by HarryR** [comment]
https://travis-ci.org/HarryR/ion/builds/394851654

I have setup Travis on my repository, it builds fine :D
