### ISSUE TITLE
can't build ion-cli on macOS 10.14

### ISSUE THREAD

**Issue by mosasiru** [clearmatics/ion#175]
Hello. I can't build ion-cli on macOS 10.14.

The environment is:
- macOS 10.14.5
- go1.8.7 darwin/amd64

```
$ go version
go version go1.8.7 darwin/amd64

$ go get -t -v ./...
github.com/ethereum/go-ethereum (download)
package github.com/ethereum/go-ethereum/crypto/sha3: cannot find package "github.com/ethereum/go-ethereum/crypto/sha3" in any of:
	/Users/yusuke.enomoto/.goenv/versions/1.12.0/src/github.com/ethereum/go-ethereum/crypto/sha3 (from $GOROOT)
	/Users/yusuke.enomoto/src/github.com/ethereum/go-ethereum/crypto/sha3 (from $GOPATH)

$ go build -o ion-cli .
# github.com/clearmatics/ion/ion-cli/utils
utils/trie.go:65:29: undefined: ethdb.NewMemDatabase
utils/trie.go:94:11: undefined: ethdb.NewMemDatabase
```

At first, the simple command `go get` failed because the latest go-ethereum v1.8.27 has no package `github.com/ethereum/go-ethereum/crypto/sha3` , so I used `Gopkg.toml` via `dep` command. If so, `libsecp256k1` dir need to be copied as the issue https://github.com/ethereum/go-ethereum/issues/2738 says.

```
$ dep ensure
$  cp -r \
  "${GOPATH}/src/github.com/ethereum/go-ethereum/crypto/secp256k1/libsecp256k1" \
  "vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/"
```

The locked go-ethereum version is [v1.8.13](https://github.com/clearmatics/ion/blob/master/ion-cli/Gopkg.toml#L32-L34).

```
$ go build -o ion-cli . 
# github.com/clearmatics/ion/ion-cli
/Users/hogehoge/.goenv/versions/1.8.7/pkg/tool/darwin_amd64/link: /Users/hogehoge/.goenv/versions/1.8.7/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)
```

This error mesage is already known in https://github.com/golang/go/issues/25908, and the comment says `go 1.11.x` will fix it.
So I tried this:
```
$ go version
go version go1.11.10 darwin/amd64
$ dep ensure
$ go build -o ion-cli .
# github.com/clearmatics/ion/ion-cli/vendor/github.com/rjeczalik/notify
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:51:216: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:165:47: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFStringCreateWithCStringNoCopy
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:166:225: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
```
This is also known bug issue in https://github.com/ethereum/go-ethereum/issues/17751 .
`geth v1.8.16` will modify the issue, but ion-cli us  `v1.8.13`.

Finally I cannot manage this problem. I guess go-ethereum version should be updated.

### Acceptance criteria
- we can build ion-cli on macOS 10.14

**Comment by Shirikatsu** [comment]
Hi @mosasiru thanks for the issue, currently investigating.

Naive diagnosis:
`go get` pulls in dependencies to `GOPATH` from master instead of specified tags. `geth` interfaces have moved on since `v1.8.13` and so `go build` fails. Need to work out how to get this to play nicely.

A temporary workaround would be to checkout the `go-ethereum` codebase to the commit specified in the `Gopkg.lock` for `v1.8.13` which is `225171a4bfcc16bd12a1906b1e0d43d0b18c353b`. Then attempt to `go build` again.

Will update if I have further news
