### ISSUE TITLE
No contract code after deployment

### ISSUE THREAD

**Issue by himankgupta31** [clearmatics/ion#184]
I trying to achieve interoperability using ION framework. 
I am using geth version 1.9.12-stable and go version go1.13.

When I am trying to deploy contract using ION-CLI, I am getting the following error:

**Waiting for contract to be deployed
no contract code after deployment**

Please help me.

**Comment by himankgupta31** [comment]
Can anybody help me ?

**Comment by Shirikatsu** [comment]
Hi there, thanks for your issue. Sorry for lateness of reply.

Are you running the master branch of the ion-cli repository?

**Comment by himankgupta31** [comment]
Yes, 
I am running the master branch of Ion-cli.

**Comment by Shirikatsu** [comment]
What sequence of commands and parameters did you use?

**Comment by himankgupta31** [comment]
I running following command to run Ethereum Private Chain:

```
geth --datadir node1/ --syncmode 'full' --port 30311 --rpc --rpcaddr 'localhost' --rpcport 8501 --rpcapi 'personal,db,eth,net,web3,txpool,miner' --networkid 1515 --gasprice '1'  --allow-insecure-unlock --unlock '0xD0C62cC112949DCf4c957B9e59cb5223CefF51F0' --password node1/password.txt --mine
```
In other Terminal 
```
./ion-cli
connectToClient http://localhost:8501

addAccount RSM /home/rsm1/devnet/node1/keystore/UTC--2020-06-25T05-38-55.860653271Z--d0c62cc112949dcf4c957b9e59cb5223ceff51f0

addContractInstance ion /home/rsm1/ion/contracts/Ion.sol

deployContract ion RSM 100000
```

**Comment by Shirikatsu** [comment]
Are you sure that the account you are using has ETH to send transactions?

**Comment by himankgupta31** [comment]
Yes.
I have pre loaded my account with ethers as it is private account running on private ethereum chain.

**Comment by Shirikatsu** [comment]
Try to increase your gas limit. 10000 Gas for contract deployment is not very much.

**Comment by himankgupta31** [comment]
Hi
Thanks. 
Ion.sol can be deployed after increasing Gas Limit.

But for the same limit, I am getting error while trying to deploy EthereumStore.sol

>>> deployContract ethstore RSM 1000000
Enter input data for parameter _ionAddr:
0x8C202Cc138f0f5D471019f1C5dBfF23D6FBeBB3D
Argument is array

Waiting for contract to be deployed
********************RSM**************
no contract code after deployment

**Comment by Shirikatsu** [comment]
Blockchains and smart contracts are not simple tools that users can utilise as plug-and-play.

If you do not understand how Ethereum works with gas, and gas limit, I suggest that you study the Ethereum blockchain. In your case, contracts cost gas to deploy, all contracts are different and will cost different amounts of gas. If you limit the gas supplied to the deployment such that you cannot deploy the contract, then the contract will not be deployed.

Before you attempt to deploy contracts or use them, you need to understand what you are attempting to do with them.

The requested `_id` is a parameter that you can give to identify your current chain. This can be any number but we recommend that you use the network id chosen in your genesis.

The `_ionAddr` parameter when you deploy `ethstore` requires you to provide the deployed contract address of the ION contract. `ethstore` will now only receive block updates from the ION contract to prevent arbitrary updates to the block state.

Thanks for your issues. We will look to clarify these concepts in the README with better descriptions of how this all works.

**Comment by himankgupta31** [comment]
Hi,

Thanks for detailed answer. It really helped me a lot to understand.

I successfully deployed ION framework on one Ethereum Private chains. 
My next question is how can we generate the transaction from one chain to another chain? I have read issue #170 .

May you please give us more clarity on that?

Furthermore, according to my understanding of ION. We can extend our ION solution by validating receiving state from another Blockchain (e.g. IOTA) but how will we validate state from Ethereum to IOTA as IOTA does not support smart contract based technology.

**Comment by himankgupta31** [comment]
@Shirikatsu 

May you please help in this regard? I will be very grateful to you.

**Comment by Shirikatsu** [comment]
Hi,

Unfortunately IOTA bridge has not been developed yet, you may develop this bridge to Ethereum. I do not have much knowledge about IOTA so I'm unable to help here. You will have to understand what is capable in IOTA and alter your mode of verification to enable cross-chain transactions between varying levels of turing-completeness.

If you understand how IOTA works at a low-level and can explain it here concisely then maybe I can provide some pointers.
