### ISSUE TITLE
Test: Submitting a deposit with a reference that already exists and has been withdrawn should fail

### ISSUE THREAD

**Issue by Shirikatsu** [clearmatics/ion#65]
Alice deposits for Bob with payment reference x. Bob deposits for Alice. Both parties successfully withdraw on the respective chains.

Now Alice attempts to deposit using payment reference x again. The deposit should fail and revert the transaction.

**Comment by daragao** [comment]
this should relate with implementations that use the Ion Core such as https://github.com/Shirikatsu/Transact-Ion
